# TODO: We need to change questions into an array of question {} with a question AND answer in them.

type Quiz {
  id: ID!
  title: String!
  author: String!
  questions: [String!]
  scores: [Int]
}

type Query {
  allQuizes: [Quiz!]
  quizesByTitle(title: String!): [Quiz!]
  quizesByAuthor(author: String!): [Quiz!]
}

mutation CreateQuiz {
  createQuiz(
    data: {
      title: "Build an awesome app!"
      author: "Conner"
      questions: ["does it work?"]
    }
  ) {
    title
    author
    questions
  }
}
